### ISSUE TITLE
按索引取字符串的编码问题

### ISSUE THREAD

**Issue by nobodxbodon** [covscript/wiki#11]
![Screen Shot 2021-03-23 at 11 33 36 PM](https://user-images.githubusercontent.com/392497/112265773-43dfee80-8c30-11eb-85f1-de6afea27eba.png)

**Comment by mikecovlee** [comment]
编码问题，CovScript默认无wchar，后期会尝试解决

**Comment by nobodxbodon** [comment]
此类语言功能相关issue可以在 https://github.com/covscript/covscript 开吗？

**Comment by mikecovlee** [comment]
可以的

**Comment by nobodxbodon** [comment]
已转 https://github.com/covscript/covscript/issues/85
