### ISSUE TITLE
正文的小标题如何更显眼

### ISSUE THREAD

**Issue by nobodxbodon** [covscript/wiki#2]
现在采用普通粗体，见下图左侧的 2.1、2.2。第一章的正文内容粗体内容较少，但第二章的多的多就感觉标题不大显眼。右侧为 word 原始效果。

之前试过用标题格式 ===，但好像不能与 `<<Anchor()>>` 合用。

![Screen Shot 2021-02-12 at 11 54 25 PM](https://user-images.githubusercontent.com/392497/107845096-e2557600-6d8d-11eb-9c15-1be5c3dc4a2b.png)

**Comment by mikecovlee** [comment]
Word和Wiki毕竟还是不能直接一对一这样整，目前这样效果也不错

**Comment by nobodxbodon** [comment]
新文档样式已改进 
![Screen Shot 2021-07-01 at 12 53 12 PM](https://user-images.githubusercontent.com/392497/124182225-6e311b80-da6b-11eb-945c-8879a4c52aa0.png)
