### ISSUE TITLE
一个疑惑

### ISSUE THREAD

**Issue by MouriNaruto** [covscript/wiki#5]
首先，祝大家新年快乐（虽然有点过时了）

倒是我得提个疑惑，那就是字符串的默认编码，我不知道是否已经默认 UTF-8 了

**Comment by mikecovlee** [comment]
为了保证最大的兼容性，目前依旧是默认ASCII

**Comment by MouriNaruto** [comment]
谢谢，建议相关内容写到文档里面会好一些（我先把问题关掉了，因为已经解决了问题）
